/**
 * generated by Xtext 2.12.0
 */
package pt.isep.edom.project.c3.dsl.domain;

import pt.isep.edom.project.c3.dsl.domain.AbstractDomainRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class DomainRuntimeModule extends AbstractDomainRuntimeModule {
}
