/**
 * generated by Xtext 2.12.0
 */
package pt.isep.edom.project.c3.dsl.domain;

import pt.isep.edom.project.c3.dsl.domain.DomainStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class DomainStandaloneSetup extends DomainStandaloneSetupGenerated {
  public static void doSetup() {
    new DomainStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
