/**
 * generated by Xtext 2.12.0
 */
package pt.isep.edom.mmapdsl.ide;

import pt.isep.edom.mmapdsl.ide.AbstractMMapDslIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MMapDslIdeModule extends AbstractMMapDslIdeModule {
}
