/**
 * generated by Xtext 2.12.0
 */
package pt.isep.edom.project.c2.dsl.rest.ide;

import pt.isep.edom.project.c2.dsl.rest.ide.AbstractRestIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class RestIdeModule extends AbstractRestIdeModule {
}
