/**
 * generated by Xtext 2.12.0
 */
package pt.isep.edom.project.c0.dsl.usecase.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import pt.isep.edom.project.c0.dsl.usecase.UseCaseRuntimeModule;
import pt.isep.edom.project.c0.dsl.usecase.UseCaseStandaloneSetup;
import pt.isep.edom.project.c0.dsl.usecase.ide.UseCaseIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class UseCaseIdeSetup extends UseCaseStandaloneSetup {
  @Override
  public Injector createInjector() {
    UseCaseRuntimeModule _useCaseRuntimeModule = new UseCaseRuntimeModule();
    UseCaseIdeModule _useCaseIdeModule = new UseCaseIdeModule();
    return Guice.createInjector(Modules2.mixin(_useCaseRuntimeModule, _useCaseIdeModule));
  }
}
