/**
 * generated by Xtext 2.12.0
 */
package pt.isep.edom.project.c0.dsl.usecase.ide;

import pt.isep.edom.project.c0.dsl.usecase.ide.AbstractUseCaseIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class UseCaseIdeModule extends AbstractUseCaseIdeModule {
}
