/**
 * generated by Xtext 2.12.0
 */
package pt.isep.edom.mmapdsl.scoping;

import pt.isep.edom.mmapdsl.scoping.AbstractMMapDslScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class MMapDslScopeProvider extends AbstractMMapDslScopeProvider {
}
