/**
 * generated by Xtext 2.12.0
 */
package pt.isep.edom.project.c2.dsl.rest.ui.contentassist;

import pt.isep.edom.project.c2.dsl.rest.ui.contentassist.AbstractRestProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class RestProposalProvider extends AbstractRestProposalProvider {
}
