/*
 * generated by Xtext 2.12.0
 */
package pt.isep.edom.mmapdsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMMapDslScopeProvider extends DelegatingScopeProvider {
}
