/**
 * generated by Xtext 2.19.0
 */
package pt.isep.edom.project.c3.dsl.ui.contentassist;

import pt.isep.edom.project.c3.dsl.ui.contentassist.AbstractDomainProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class DomainProposalProvider extends AbstractDomainProposalProvider {
}
