/**
 * generated by Xtext 2.12.0
 */
package pt.isep.edom.project.c1.dsl.nav.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import pt.isep.edom.project.c1.dsl.nav.ui.AbstractNavUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class NavUiModule extends AbstractNavUiModule {
  public NavUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
