/**
 * generated by Xtext 2.12.0
 */
package pt.isep.edom.project.c1.dsl.nav.validation;

import pt.isep.edom.project.c1.dsl.nav.validation.AbstractNavValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class NavValidator extends AbstractNavValidator {
}
