/*
 * generated by Xtext 2.12.0
 */
package pt.isep.edom.mmapdsl.tests

import com.google.inject.Inject
import pt.isep.edom.mindmap.Map
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(MMapDslInjectorProvider)
class MMapDslParsingTest {
	@Inject
	ParseHelper<Map> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			Map {title Agenda elements {
				Topic Contacts {
					description "descrição" start "2019-10-11" end "2020-01-01"}
				, Topic ABC{
					description "descrição" start "2019-10-11" end "2020-01-01" parent Contacts}
			}}
		''') 
		Assert.assertNotNull(result)
		Assert.assertTrue(result.eResource.errors.isEmpty)
	}
	
	@Test
	def void loadModel2() {
		val result = parseHelper.parse('''
			Map {{
				Topic Contacts {
					description "descrição" start "2019-10-11" end "2020-01-01"}
				, Topic ABC{
					description "descrição" start "2019-10-11" end "2020-01-01" parent Contacts}
			}}
		''') 
		Assert.assertNotNull(result)
		Assert.assertFalse(result.eResource.errors.isEmpty)
	}
	
	@Test
	def void loadModel3() {
		val result = parseHelper.parse('''
			Map {{
				Topic Contacts {
					description "descrição" start "2019-10-11" end "2020-01-01", Topic ABC{
										description "descrição" start "2019-10-11" end "2020-01-01" parent Contacts}}
				
			}}
		''') 
		Assert.assertNotNull(result)
		Assert.assertFalse(result.eResource.errors.isEmpty)
	}

}
