/**
 * generated by Xtext 2.12.0
 */
package pt.isep.edom.project.c0.dsl.usecase.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
@SuppressWarnings("all")
public class UseCaseQuickfixProvider extends DefaultQuickfixProvider {
}
