/**
 * generated by Xtext 2.12.0
 */
package pt.isep.edom.project.c1.dsl.nav.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import pt.isep.edom.project.c1.dsl.nav.NavRuntimeModule;
import pt.isep.edom.project.c1.dsl.nav.NavStandaloneSetup;
import pt.isep.edom.project.c1.dsl.nav.ide.NavIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class NavIdeSetup extends NavStandaloneSetup {
  @Override
  public Injector createInjector() {
    NavRuntimeModule _navRuntimeModule = new NavRuntimeModule();
    NavIdeModule _navIdeModule = new NavIdeModule();
    return Guice.createInjector(Modules2.mixin(_navRuntimeModule, _navIdeModule));
  }
}
