/**
 * generated by Xtext 2.12.0
 */
package pt.isep.edom.project.c1.dsl.nav.ide;

import pt.isep.edom.project.c1.dsl.nav.ide.AbstractNavIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class NavIdeModule extends AbstractNavIdeModule {
}
