/**
 * generated by Xtext 2.12.0
 */
package pt.isep.edom.project.c4.dsl.dbase;

import pt.isep.edom.project.c4.dsl.dbase.DbaseStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class DbaseStandaloneSetup extends DbaseStandaloneSetupGenerated {
  public static void doSetup() {
    new DbaseStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
