/**
 * generated by Xtext 2.12.0
 */
package pt.isep.edom.project.c4.dsl.dbase;

import pt.isep.edom.project.c4.dsl.dbase.AbstractDbaseRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class DbaseRuntimeModule extends AbstractDbaseRuntimeModule {
}
