/**
 * generated by Xtext 2.12.0
 */
package pt.isep.edom.project.c0.dsl.usecase.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import pt.isep.edom.project.c0.dsl.usecase.ui.AbstractUseCaseUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class UseCaseUiModule extends AbstractUseCaseUiModule {
  public UseCaseUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
