/**
 * generated by Xtext 2.19.0
 */
package pt.isep.edom.project.c3.dsl;

import pt.isep.edom.project.c3.dsl.DomainStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class DomainStandaloneSetup extends DomainStandaloneSetupGenerated {
  public static void doSetup() {
    new DomainStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
