/**
 * generated by Xtext 2.12.0
 */
package pt.isep.edom.mmapdsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import pt.isep.edom.mmapdsl.ui.AbstractMMapDslUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class MMapDslUiModule extends AbstractMMapDslUiModule {
  public MMapDslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
