/**
 * generated by Xtext 2.12.0
 */
package pt.isep.edom.mmapdsl.validation;

import pt.isep.edom.mmapdsl.validation.AbstractMMapDslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class MMapDslValidator extends AbstractMMapDslValidator {
}
