/**
 * generated by Xtext 2.12.0
 */
package pt.isep.edom.project.c4.dsl.dbase.ide;

import pt.isep.edom.project.c4.dsl.dbase.ide.AbstractDbaseIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class DbaseIdeModule extends AbstractDbaseIdeModule {
}
