<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="gorgeousfood" nsURI="http://www.example.org/gorgeousfood" nsPrefix="gorgeousfood">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
    <details key="ecore.xml.type" value="http://www.eclipse.org/emf/2003/XMLType"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Meal">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="mustHaveID mustHavePositiveID mustHaveDescription"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="mustHaveID" value="not MealID.oclIsInvalid()"/>
      <details key="mustHavePositiveID" value="MealID > 0"/>
      <details key="mustHaveDescription" value="not Description.oclIsInvalid()"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="MealID" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="descriptor" upperBound="-1"
        eType="#//Descriptor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ingredient" upperBound="-1"
        eType="#//Ingredient" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MealItem">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="mustHaveID mustHavePositiveID mustHaveExpDate mustHavePrdDate expDateNextPrdDate"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="mustHaveID" value="not MealItemID.oclIsInvalid()"/>
      <details key="mustHavePositiveID" value="MealItemID > 0"/>
      <details key="mustHaveExpDate" value="not ExpDate.oclIsInvalid()"/>
      <details key="mustHavePrdDate" value="not PrdDate.oclIsInvalid()"/>
      <details key="expDateNextPrdDate" value="self.ExpDate > self.PrdDate"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="MealItemID" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ExpDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="PrdDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="meal" upperBound="-1" eType="#//Meal"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sale">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="mustHaveID mustHavePositiveID mustHaveDate"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="mustHaveID" value="not SaleID.oclIsInvalid()"/>
      <details key="mustHavePositiveID" value="SaleID > 0"/>
      <details key="mustHaveDate" value="not Date.oclIsInvalid()"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SaleID" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mealitem" upperBound="-1"
        eType="#//MealItem" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Descriptor">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="mustHaveID mustHavePositiveID mustHaveDescription"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="mustHaveID" value="not DescriptorID.oclIsInvalid()"/>
      <details key="mustHavePositiveID" value="DescriptorID > 0"/>
      <details key="mustHaveDescription" value="not Description.oclIsInvalid()"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DescriptorID" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ingredient">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="mustHaveID mustHavePositiveID mustHaveDescription"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="mustHaveID" value="not IngredientID.oclIsInvalid()"/>
      <details key="mustHavePositiveID" value="IngredientID > 0"/>
      <details key="mustHaveDescription" value="not Description.oclIsInvalid()"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="IngredientID" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
