/*
 * generated by Xtext 2.12.0
 */
package pt.isep.edom.mmapdsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import pt.isep.edom.mmapdsl.ui.internal.MmapdslActivator;

public class MMapDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MmapdslActivator.getInstance().getInjector("pt.isep.edom.mmapdsl.MMapDsl");
	}

}
