/**
 * generated by Xtext 2.12.0
 */
package pt.isep.edom.project.c1.dsl.nav.formatting2;

import com.google.inject.Inject;
import java.util.Arrays;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import pt.isep.edom.project.c1.dsl.nav.services.NavGrammarAccess;
import pt.isep.edom.project.c1.mm.nav.Menu;
import pt.isep.edom.project.c1.mm.nav.NavModel;
import pt.isep.edom.project.c1.mm.nav.Page;

@SuppressWarnings("all")
public class NavFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private NavGrammarAccess _navGrammarAccess;
  
  protected void _format(final NavModel navModel, @Extension final IFormattableDocument document) {
    document.<Menu>format(navModel.getMenu());
  }
  
  protected void _format(final Menu menu, @Extension final IFormattableDocument document) {
    EList<Page> _pages = menu.getPages();
    for (final Page page : _pages) {
      document.<Page>format(page);
    }
  }
  
  public void format(final Object menu, final IFormattableDocument document) {
    if (menu instanceof XtextResource) {
      _format((XtextResource)menu, document);
      return;
    } else if (menu instanceof Menu) {
      _format((Menu)menu, document);
      return;
    } else if (menu instanceof NavModel) {
      _format((NavModel)menu, document);
      return;
    } else if (menu instanceof EObject) {
      _format((EObject)menu, document);
      return;
    } else if (menu == null) {
      _format((Void)null, document);
      return;
    } else if (menu != null) {
      _format(menu, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(menu, document).toString());
    }
  }
}
