/*
 * generated by Xtext 2.19.0
 */
package pt.isep.edom.project.c3.dsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractEnumRuleElementFinder;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class DomainGrammarAccess extends AbstractGrammarElementFinder {
	
	public class DomainModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "pt.isep.edom.project.c3.dsl.Domain.DomainModel");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cDomainModelAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cDomainModelKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cEntitiesKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cEntitiesAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cEntitiesEntityParserRuleCall_4_2_0 = (RuleCall)cEntitiesAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cEntitiesAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cEntitiesEntityParserRuleCall_4_3_1_0 = (RuleCall)cEntitiesAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cValueobjectKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cValueobjectAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cValueobjectValueObjectParserRuleCall_5_2_0 = (RuleCall)cValueobjectAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cValueobjectAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cValueobjectValueObjectParserRuleCall_5_3_1_0 = (RuleCall)cValueobjectAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//DomainModel:
		//	{DomainModel}
		//	'DomainModel'
		//	name=EString
		//	'{' ('entities' '{' entities+=Entity ("," entities+=Entity)* '}')? ('valueobject' '{' valueobject+=ValueObject (","
		//	valueobject+=ValueObject)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{DomainModel} 'DomainModel' name=EString '{' ('entities' '{' entities+=Entity ("," entities+=Entity)* '}')?
		//('valueobject' '{' valueobject+=ValueObject ("," valueobject+=ValueObject)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//{DomainModel}
		public Action getDomainModelAction_0() { return cDomainModelAction_0; }
		
		//'DomainModel'
		public Keyword getDomainModelKeyword_1() { return cDomainModelKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('entities' '{' entities+=Entity ("," entities+=Entity)* '}')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'entities'
		public Keyword getEntitiesKeyword_4_0() { return cEntitiesKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//entities+=Entity
		public Assignment getEntitiesAssignment_4_2() { return cEntitiesAssignment_4_2; }
		
		//Entity
		public RuleCall getEntitiesEntityParserRuleCall_4_2_0() { return cEntitiesEntityParserRuleCall_4_2_0; }
		
		//("," entities+=Entity)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//entities+=Entity
		public Assignment getEntitiesAssignment_4_3_1() { return cEntitiesAssignment_4_3_1; }
		
		//Entity
		public RuleCall getEntitiesEntityParserRuleCall_4_3_1_0() { return cEntitiesEntityParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//('valueobject' '{' valueobject+=ValueObject ("," valueobject+=ValueObject)* '}')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'valueobject'
		public Keyword getValueobjectKeyword_5_0() { return cValueobjectKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//valueobject+=ValueObject
		public Assignment getValueobjectAssignment_5_2() { return cValueobjectAssignment_5_2; }
		
		//ValueObject
		public RuleCall getValueobjectValueObjectParserRuleCall_5_2_0() { return cValueobjectValueObjectParserRuleCall_5_2_0; }
		
		//("," valueobject+=ValueObject)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//valueobject+=ValueObject
		public Assignment getValueobjectAssignment_5_3_1() { return cValueobjectAssignment_5_3_1; }
		
		//ValueObject
		public RuleCall getValueobjectValueObjectParserRuleCall_5_3_1_0() { return cValueobjectValueObjectParserRuleCall_5_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "pt.isep.edom.project.c3.dsl.Domain.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class EntityElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "pt.isep.edom.project.c3.dsl.Domain.Entity");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cRootAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cRootRootKeyword_0_0 = (Keyword)cRootAssignment_0.eContents().get(0);
		private final Keyword cEntityKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cFieldsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cFieldsAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cFieldsFieldParserRuleCall_4_2_0 = (RuleCall)cFieldsAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cFieldsAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cFieldsFieldParserRuleCall_4_3_1_0 = (RuleCall)cFieldsAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cReferencesKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cReferencesAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cReferencesReferenceParserRuleCall_5_2_0 = (RuleCall)cReferencesAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cReferencesAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cReferencesReferenceParserRuleCall_5_3_1_0 = (RuleCall)cReferencesAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Entity:
		//	root?='root'
		//	'Entity'
		//	name=EString
		//	'{' ('fields' '{' fields+=Field ("," fields+=Field)* '}')? ('references' '{' references+=Reference (","
		//	references+=Reference)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//root?='root' 'Entity' name=EString '{' ('fields' '{' fields+=Field ("," fields+=Field)* '}')? ('references' '{'
		//references+=Reference ("," references+=Reference)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//root?='root'
		public Assignment getRootAssignment_0() { return cRootAssignment_0; }
		
		//'root'
		public Keyword getRootRootKeyword_0_0() { return cRootRootKeyword_0_0; }
		
		//'Entity'
		public Keyword getEntityKeyword_1() { return cEntityKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('fields' '{' fields+=Field ("," fields+=Field)* '}')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'fields'
		public Keyword getFieldsKeyword_4_0() { return cFieldsKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//fields+=Field
		public Assignment getFieldsAssignment_4_2() { return cFieldsAssignment_4_2; }
		
		//Field
		public RuleCall getFieldsFieldParserRuleCall_4_2_0() { return cFieldsFieldParserRuleCall_4_2_0; }
		
		//("," fields+=Field)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//fields+=Field
		public Assignment getFieldsAssignment_4_3_1() { return cFieldsAssignment_4_3_1; }
		
		//Field
		public RuleCall getFieldsFieldParserRuleCall_4_3_1_0() { return cFieldsFieldParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//('references' '{' references+=Reference ("," references+=Reference)* '}')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'references'
		public Keyword getReferencesKeyword_5_0() { return cReferencesKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//references+=Reference
		public Assignment getReferencesAssignment_5_2() { return cReferencesAssignment_5_2; }
		
		//Reference
		public RuleCall getReferencesReferenceParserRuleCall_5_2_0() { return cReferencesReferenceParserRuleCall_5_2_0; }
		
		//("," references+=Reference)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//references+=Reference
		public Assignment getReferencesAssignment_5_3_1() { return cReferencesAssignment_5_3_1; }
		
		//Reference
		public RuleCall getReferencesReferenceParserRuleCall_5_3_1_0() { return cReferencesReferenceParserRuleCall_5_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class ValueObjectElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "pt.isep.edom.project.c3.dsl.Domain.ValueObject");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cIsIdAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cIsIdIsIdKeyword_0_0 = (Keyword)cIsIdAssignment_0.eContents().get(0);
		private final Keyword cValueObjectKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cFieldKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cFieldAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cFieldFieldParserRuleCall_5_0 = (RuleCall)cFieldAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//ValueObject:
		//	isId?='isId'
		//	'ValueObject'
		//	name=EString
		//	'{'
		//	'field' field=Field
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//isId?='isId' 'ValueObject' name=EString '{' 'field' field=Field '}'
		public Group getGroup() { return cGroup; }
		
		//isId?='isId'
		public Assignment getIsIdAssignment_0() { return cIsIdAssignment_0; }
		
		//'isId'
		public Keyword getIsIdIsIdKeyword_0_0() { return cIsIdIsIdKeyword_0_0; }
		
		//'ValueObject'
		public Keyword getValueObjectKeyword_1() { return cValueObjectKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//'field'
		public Keyword getFieldKeyword_4() { return cFieldKeyword_4; }
		
		//field=Field
		public Assignment getFieldAssignment_5() { return cFieldAssignment_5; }
		
		//Field
		public RuleCall getFieldFieldParserRuleCall_5_0() { return cFieldFieldParserRuleCall_5_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class FieldElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "pt.isep.edom.project.c3.dsl.Domain.Field");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cFieldAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cFieldKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cTypeKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cTypeAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cTypeFieldTypeEnumRuleCall_4_1_0 = (RuleCall)cTypeAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Field:
		//	{Field}
		//	'Field'
		//	name=EString
		//	'{' ('type' type=FieldType)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Field} 'Field' name=EString '{' ('type' type=FieldType)? '}'
		public Group getGroup() { return cGroup; }
		
		//{Field}
		public Action getFieldAction_0() { return cFieldAction_0; }
		
		//'Field'
		public Keyword getFieldKeyword_1() { return cFieldKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('type' type=FieldType)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'type'
		public Keyword getTypeKeyword_4_0() { return cTypeKeyword_4_0; }
		
		//type=FieldType
		public Assignment getTypeAssignment_4_1() { return cTypeAssignment_4_1; }
		
		//FieldType
		public RuleCall getTypeFieldTypeEnumRuleCall_4_1_0() { return cTypeFieldTypeEnumRuleCall_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class ReferenceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "pt.isep.edom.project.c3.dsl.Domain.Reference");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cReferenceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cUpperBoundKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cUpperBoundAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cUpperBoundEIntParserRuleCall_4_0 = (RuleCall)cUpperBoundAssignment_4.eContents().get(0);
		private final Keyword cLowerBoundKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cLowerBoundAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cLowerBoundEIntParserRuleCall_6_0 = (RuleCall)cLowerBoundAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cEntityKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cEntityAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final CrossReference cEntityEntityCrossReference_7_1_0 = (CrossReference)cEntityAssignment_7_1.eContents().get(0);
		private final RuleCall cEntityEntityEStringParserRuleCall_7_1_0_1 = (RuleCall)cEntityEntityCrossReference_7_1_0.eContents().get(1);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cValueobjectKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cValueobjectAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final CrossReference cValueobjectValueObjectCrossReference_8_1_0 = (CrossReference)cValueobjectAssignment_8_1.eContents().get(0);
		private final RuleCall cValueobjectValueObjectEStringParserRuleCall_8_1_0_1 = (RuleCall)cValueobjectValueObjectCrossReference_8_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//Reference:
		//	'Reference'
		//	name=EString
		//	'{'
		//	'upperBound' upperBound=EInt
		//	'lowerBound' lowerBound=EInt ('entity' entity=[Entity|EString])? ('valueobject' valueobject=[ValueObject|EString])?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Reference' name=EString '{' 'upperBound' upperBound=EInt 'lowerBound' lowerBound=EInt ('entity'
		//entity=[Entity|EString])? ('valueobject' valueobject=[ValueObject|EString])? '}'
		public Group getGroup() { return cGroup; }
		
		//'Reference'
		public Keyword getReferenceKeyword_0() { return cReferenceKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'upperBound'
		public Keyword getUpperBoundKeyword_3() { return cUpperBoundKeyword_3; }
		
		//upperBound=EInt
		public Assignment getUpperBoundAssignment_4() { return cUpperBoundAssignment_4; }
		
		//EInt
		public RuleCall getUpperBoundEIntParserRuleCall_4_0() { return cUpperBoundEIntParserRuleCall_4_0; }
		
		//'lowerBound'
		public Keyword getLowerBoundKeyword_5() { return cLowerBoundKeyword_5; }
		
		//lowerBound=EInt
		public Assignment getLowerBoundAssignment_6() { return cLowerBoundAssignment_6; }
		
		//EInt
		public RuleCall getLowerBoundEIntParserRuleCall_6_0() { return cLowerBoundEIntParserRuleCall_6_0; }
		
		//('entity' entity=[Entity|EString])?
		public Group getGroup_7() { return cGroup_7; }
		
		//'entity'
		public Keyword getEntityKeyword_7_0() { return cEntityKeyword_7_0; }
		
		//entity=[Entity|EString]
		public Assignment getEntityAssignment_7_1() { return cEntityAssignment_7_1; }
		
		//[Entity|EString]
		public CrossReference getEntityEntityCrossReference_7_1_0() { return cEntityEntityCrossReference_7_1_0; }
		
		//EString
		public RuleCall getEntityEntityEStringParserRuleCall_7_1_0_1() { return cEntityEntityEStringParserRuleCall_7_1_0_1; }
		
		//('valueobject' valueobject=[ValueObject|EString])?
		public Group getGroup_8() { return cGroup_8; }
		
		//'valueobject'
		public Keyword getValueobjectKeyword_8_0() { return cValueobjectKeyword_8_0; }
		
		//valueobject=[ValueObject|EString]
		public Assignment getValueobjectAssignment_8_1() { return cValueobjectAssignment_8_1; }
		
		//[ValueObject|EString]
		public CrossReference getValueobjectValueObjectCrossReference_8_1_0() { return cValueobjectValueObjectCrossReference_8_1_0; }
		
		//EString
		public RuleCall getValueobjectValueObjectEStringParserRuleCall_8_1_0_1() { return cValueobjectValueObjectEStringParserRuleCall_8_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "pt.isep.edom.project.c3.dsl.Domain.EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean ecore::EBoolean:
		//	'true' | 'false';
		@Override public ParserRule getRule() { return rule; }
		
		//'true' | 'false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'true'
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }
		
		//'false'
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "pt.isep.edom.project.c3.dsl.Domain.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt ecore::EInt:
		//	'-'? INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	
	public class FieldTypeElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "pt.isep.edom.project.c3.dsl.Domain.FieldType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cSTRINGEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cSTRINGSTRINGKeyword_0_0 = (Keyword)cSTRINGEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cINTEGEREnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cINTEGERINTEGERKeyword_1_0 = (Keyword)cINTEGEREnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cREALEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cREALREALKeyword_2_0 = (Keyword)cREALEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cBOOLEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cBOOLBOOLKeyword_3_0 = (Keyword)cBOOLEnumLiteralDeclaration_3.eContents().get(0);
		
		//enum FieldType:
		//	STRING | INTEGER | REAL | BOOL;
		public EnumRule getRule() { return rule; }
		
		//STRING | INTEGER | REAL | BOOL
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public EnumLiteralDeclaration getSTRINGEnumLiteralDeclaration_0() { return cSTRINGEnumLiteralDeclaration_0; }
		
		//'STRING'
		public Keyword getSTRINGSTRINGKeyword_0_0() { return cSTRINGSTRINGKeyword_0_0; }
		
		//INTEGER
		public EnumLiteralDeclaration getINTEGEREnumLiteralDeclaration_1() { return cINTEGEREnumLiteralDeclaration_1; }
		
		//'INTEGER'
		public Keyword getINTEGERINTEGERKeyword_1_0() { return cINTEGERINTEGERKeyword_1_0; }
		
		//REAL
		public EnumLiteralDeclaration getREALEnumLiteralDeclaration_2() { return cREALEnumLiteralDeclaration_2; }
		
		//'REAL'
		public Keyword getREALREALKeyword_2_0() { return cREALREALKeyword_2_0; }
		
		//BOOL
		public EnumLiteralDeclaration getBOOLEnumLiteralDeclaration_3() { return cBOOLEnumLiteralDeclaration_3; }
		
		//'BOOL'
		public Keyword getBOOLBOOLKeyword_3_0() { return cBOOLBOOLKeyword_3_0; }
	}
	
	private final DomainModelElements pDomainModel;
	private final EStringElements pEString;
	private final EntityElements pEntity;
	private final ValueObjectElements pValueObject;
	private final FieldElements pField;
	private final ReferenceElements pReference;
	private final EBooleanElements pEBoolean;
	private final FieldTypeElements eFieldType;
	private final EIntElements pEInt;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public DomainGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pDomainModel = new DomainModelElements();
		this.pEString = new EStringElements();
		this.pEntity = new EntityElements();
		this.pValueObject = new ValueObjectElements();
		this.pField = new FieldElements();
		this.pReference = new ReferenceElements();
		this.pEBoolean = new EBooleanElements();
		this.eFieldType = new FieldTypeElements();
		this.pEInt = new EIntElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("pt.isep.edom.project.c3.dsl.Domain".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//DomainModel:
	//	{DomainModel}
	//	'DomainModel'
	//	name=EString
	//	'{' ('entities' '{' entities+=Entity ("," entities+=Entity)* '}')? ('valueobject' '{' valueobject+=ValueObject (","
	//	valueobject+=ValueObject)* '}')?
	//	'}';
	public DomainModelElements getDomainModelAccess() {
		return pDomainModel;
	}
	
	public ParserRule getDomainModelRule() {
		return getDomainModelAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//Entity:
	//	root?='root'
	//	'Entity'
	//	name=EString
	//	'{' ('fields' '{' fields+=Field ("," fields+=Field)* '}')? ('references' '{' references+=Reference (","
	//	references+=Reference)* '}')?
	//	'}';
	public EntityElements getEntityAccess() {
		return pEntity;
	}
	
	public ParserRule getEntityRule() {
		return getEntityAccess().getRule();
	}
	
	//ValueObject:
	//	isId?='isId'
	//	'ValueObject'
	//	name=EString
	//	'{'
	//	'field' field=Field
	//	'}';
	public ValueObjectElements getValueObjectAccess() {
		return pValueObject;
	}
	
	public ParserRule getValueObjectRule() {
		return getValueObjectAccess().getRule();
	}
	
	//Field:
	//	{Field}
	//	'Field'
	//	name=EString
	//	'{' ('type' type=FieldType)?
	//	'}';
	public FieldElements getFieldAccess() {
		return pField;
	}
	
	public ParserRule getFieldRule() {
		return getFieldAccess().getRule();
	}
	
	//Reference:
	//	'Reference'
	//	name=EString
	//	'{'
	//	'upperBound' upperBound=EInt
	//	'lowerBound' lowerBound=EInt ('entity' entity=[Entity|EString])? ('valueobject' valueobject=[ValueObject|EString])?
	//	'}';
	public ReferenceElements getReferenceAccess() {
		return pReference;
	}
	
	public ParserRule getReferenceRule() {
		return getReferenceAccess().getRule();
	}
	
	//EBoolean ecore::EBoolean:
	//	'true' | 'false';
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}
	
	//enum FieldType:
	//	STRING | INTEGER | REAL | BOOL;
	public FieldTypeElements getFieldTypeAccess() {
		return eFieldType;
	}
	
	public EnumRule getFieldTypeRule() {
		return getFieldTypeAccess().getRule();
	}
	
	//EInt ecore::EInt:
	//	'-'? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
