/**
 * generated by Xtext 2.12.0
 */
package pt.isep.edom.mmapdsl;

import org.eclipse.xtext.conversion.IValueConverterService;
import pt.isep.edom.mmapdsl.AbstractMMapDslRuntimeModule;
import pt.isep.edom.mmapdsl.converter.MMapDslValueConverter;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class MMapDslRuntimeModule extends AbstractMMapDslRuntimeModule {
  @Override
  public Class<? extends IValueConverterService> bindIValueConverterService() {
    return MMapDslValueConverter.class;
  }
}
