/**
 * generated by Xtext 2.12.0
 */
package pt.isep.edom.project.c1.dsl.nav;

import pt.isep.edom.project.c1.dsl.nav.AbstractNavRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class NavRuntimeModule extends AbstractNavRuntimeModule {
}
