/**
 * generated by Xtext 2.12.0
 */
package pt.isep.edom.project.c1.dsl.nav;

import pt.isep.edom.project.c1.dsl.nav.NavStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class NavStandaloneSetup extends NavStandaloneSetupGenerated {
  public static void doSetup() {
    new NavStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
