/**
 * generated by Xtext 2.12.0
 */
package pt.isep.edom.mmapdsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import pt.isep.edom.mmapdsl.MMapDslRuntimeModule;
import pt.isep.edom.mmapdsl.MMapDslStandaloneSetup;
import pt.isep.edom.mmapdsl.ide.MMapDslIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class MMapDslIdeSetup extends MMapDslStandaloneSetup {
  @Override
  public Injector createInjector() {
    MMapDslRuntimeModule _mMapDslRuntimeModule = new MMapDslRuntimeModule();
    MMapDslIdeModule _mMapDslIdeModule = new MMapDslIdeModule();
    return Guice.createInjector(Modules2.mixin(_mMapDslRuntimeModule, _mMapDslIdeModule));
  }
}
