/*
 * generated by Xtext 2.19.0
 */
package pt.isep.edom.project.c3.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDomainScopeProvider extends DelegatingScopeProvider {
}
