/*
 * generated by Xtext 2.12.0
 */
package pt.isep.edom.mmapdsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MMapDslStandaloneSetup extends MMapDslStandaloneSetupGenerated {

	def static void doSetup() {
		new MMapDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
