/**
 * generated by Xtext 2.12.0
 */
package pt.isep.edom.project.c4.dsl.dbase.ui.contentassist;

import pt.isep.edom.project.c4.dsl.dbase.ui.contentassist.AbstractDbaseProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class DbaseProposalProvider extends AbstractDbaseProposalProvider {
}
