/**
 * generated by Xtext 2.12.0
 */
package pt.isep.edom.project.c4.dsl.dbase.ui.labeling;

import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

/**
 * Provides labels for IEObjectDescriptions and IResourceDescriptions.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
@SuppressWarnings("all")
public class DbaseDescriptionLabelProvider extends DefaultDescriptionLabelProvider {
}
