/**
 * generated by Xtext 2.12.0
 */
package pt.isep.edom.project.c4.dsl.dbase.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import pt.isep.edom.project.c4.dsl.dbase.ui.AbstractDbaseUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class DbaseUiModule extends AbstractDbaseUiModule {
  public DbaseUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
