/*
 * generated by Xtext 2.12.0
 */
package pt.isep.edom.mmapdsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MMapDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("pt/isep/edom/mmapdsl/parser/antlr/internal/InternalMMapDsl.tokens");
	}
}
