/*
 * generated by Xtext 2.19.0
 */
package pt.isep.edom.project.c3.dsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class DomainStandaloneSetup extends DomainStandaloneSetupGenerated {

	def static void doSetup() {
		new DomainStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
