/*
 * generated by Xtext 2.19.0
 */
package pt.isep.edom.project.c3.dsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class DomainRuntimeModule extends AbstractDomainRuntimeModule {
}
