/**
 * generated by Xtext 2.12.0
 */
package pt.isep.edom.mmapdsl.ui.contentassist;

import pt.isep.edom.mmapdsl.ui.contentassist.AbstractMMapDslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class MMapDslProposalProvider extends AbstractMMapDslProposalProvider {
}
