/**
 * generated by Xtext 2.19.0
 */
package pt.isep.edom.project.c3.dsl.ide;

import pt.isep.edom.project.c3.dsl.ide.AbstractDomainIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class DomainIdeModule extends AbstractDomainIdeModule {
}
