/**
 * generated by Xtext 2.12.0
 */
package pt.isep.edom.project.c2.dsl.rest;

import pt.isep.edom.project.c2.dsl.rest.AbstractRestRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class RestRuntimeModule extends AbstractRestRuntimeModule {
}
