/**
 * generated by Xtext 2.12.0
 */
package pt.isep.edom.project.c2.dsl.rest.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import pt.isep.edom.project.c2.dsl.rest.ui.AbstractRestUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class RestUiModule extends AbstractRestUiModule {
  public RestUiModule(final AbstractUIPlugin arg0) {
    super(arg0);
  }
}
