/*
 * generated by Xtext 2.19.0
 */
package pt.isep.edom.project.c3.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DomainAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("pt/isep/edom/project/c3/dsl/parser/antlr/internal/InternalDomain.tokens");
	}
}
