/**
 * generated by Xtext 2.19.0
 */
package pt.isep.edom.project.c3.dsl.validation;

import pt.isep.edom.project.c3.dsl.validation.AbstractDomainValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class DomainValidator extends AbstractDomainValidator {
}
