/*
 * generated by Xtext 2.19.0
 */
package pt.isep.edom.project.c3.dsl.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import pt.isep.edom.project.c3.dsl.domain.ui.internal.DomainActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DomainExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(DomainActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		DomainActivator activator = DomainActivator.getInstance();
		return activator != null ? activator.getInjector(DomainActivator.PT_ISEP_EDOM_PROJECT_C3_DSL_DOMAIN) : null;
	}

}
