/**
 * generated by Xtext 2.12.0
 */
package pt.isep.edom.project.c0.dsl.usecase;

import pt.isep.edom.project.c0.dsl.usecase.UseCaseStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class UseCaseStandaloneSetup extends UseCaseStandaloneSetupGenerated {
  public static void doSetup() {
    new UseCaseStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
