/**
 * generated by Xtext 2.12.0
 */
package pt.isep.edom.project.c0.dsl.usecase;

import pt.isep.edom.project.c0.dsl.usecase.AbstractUseCaseRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class UseCaseRuntimeModule extends AbstractUseCaseRuntimeModule {
}
