/**
 * generated by Xtext 2.12.0
 */
package pt.isep.edom.project.c3.dsl.domain.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import pt.isep.edom.project.c3.dsl.domain.ui.AbstractDomainUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class DomainUiModule extends AbstractDomainUiModule {
  public DomainUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
