/**
 * generated by Xtext 2.12.0
 */
package pt.isep.edom.mmapdsl;

import pt.isep.edom.mmapdsl.MMapDslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class MMapDslStandaloneSetup extends MMapDslStandaloneSetupGenerated {
  public static void doSetup() {
    new MMapDslStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
