/**
 * generated by Xtext 2.12.0
 */
package pt.isep.edom.project.c3.dsl.domain.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import pt.isep.edom.project.c3.dsl.domain.DomainRuntimeModule;
import pt.isep.edom.project.c3.dsl.domain.DomainStandaloneSetup;
import pt.isep.edom.project.c3.dsl.domain.ide.DomainIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class DomainIdeSetup extends DomainStandaloneSetup {
  @Override
  public Injector createInjector() {
    DomainRuntimeModule _domainRuntimeModule = new DomainRuntimeModule();
    DomainIdeModule _domainIdeModule = new DomainIdeModule();
    return Guice.createInjector(Modules2.mixin(_domainRuntimeModule, _domainIdeModule));
  }
}
