/**
 * generated by Xtext 2.12.0
 */
package pt.isep.edom.project.c3.dsl.domain.ide;

import pt.isep.edom.project.c3.dsl.domain.ide.AbstractDomainIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class DomainIdeModule extends AbstractDomainIdeModule {
}
