/*
 * generated by Xtext 2.12.0
 */
package pt.isep.edom.mmapdsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import pt.isep.edom.mmapdsl.parser.antlr.internal.InternalMMapDslParser;
import pt.isep.edom.mmapdsl.services.MMapDslGrammarAccess;

public class MMapDslParser extends AbstractAntlrParser {

	@Inject
	private MMapDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMMapDslParser createParser(XtextTokenStream stream) {
		return new InternalMMapDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Map";
	}

	public MMapDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MMapDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
